[workspace]
authors = ["Riccardo Cappuzzo <riccardo.cappuzzo@gmail.com>"]
channels = ["conda-forge"]
name = "caparezzology"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
requests = ">=2.32.5,<3"
polars = ">=1.35.2,<2"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.8,<4"
ipython = ">=9.7.0,<10"
ipykernel = ">=7.1.0,<8"
beautifulsoup4 = ">=4.14.2,<5"
transformers = ">=4.57.3,<5"
tqdm = ">=4.67.1,<5"

[pypi-dependencies]
torch = ">=2.9.1, <3"
torchvision = ">=0.24.1, <0.25"
